include("fileHandler.jl")

I=readFromFile(input_file)["I"][1]
U=readFromFile(input_file)["U"][1]
S=readFromFile(input_file)["S"][1]
D=H=readFromFile(input_file)["D"][1]
R=readFromFile(input_file)["R"][1]
M=readFromFile(input_file)["M"][1]

Preferanse_ir=readFromFile(input_file)["Preferanse_ir"]
L_isA=readFromFile(input_file)["L_isA"]
T_im=readFromFile(input_file)["T_im"]
G=readFromFile(input_file)["G"][1]
N_sd=readFromFile(input_file)["N_sd"]
S_sd=readFromFile(input_file)["S_sd"]
D_iuW=readFromFile(input_file)["D_iuW"]
D_iuW_NY=D_iuW/sum(D_iuW)
K_dr=readFromFile(input_file)["K_dr"]
D_iuD=readFromFile(input_file)["D_iuD"]
B_iu=readFromFile(input_file)["B_iu"]
L_sd=readFromFile(input_file)["L_sd"]
A_id=readFromFile(input_file)["A_id"]
Q_d=readFromFile(input_file)["Q_d"][1]
Q_w=readFromFile(input_file)["Q_w"][1]
Percentage=readFromFile(input_file)["Percentage"][1]
E_iu1=readFromFile(input_file)["E_iu1"]
E_iu2=readFromFile(input_file)["E_iu2"]
E_iu3=readFromFile(input_file)["E_iu3"]
E_iu4=readFromFile(input_file)["E_iu4"]
E_iu5=readFromFile(input_file)["E_iu5"]
E_iud=cat(dims=3,E_iu1,E_iu2,E_iu3, E_iu4, E_iu5)
MDT_interpretation_time_i=readFromFile(input_file)["MDT_interpretation_time_i"]
scanning_time_sd=readFromFile(input_file)["scanning_time_sd"]
